---
- name: install deploy script
  hosts: all

  tasks:
    - name: copy ipfs key
      ansible.builtin.copy:
        src: "{{ ipfs_key_name }}.key"
        dest: /tmp/totp.key

    - name: copy ipfs key import script
      ansible.builtin.template:
        src: import_ipfs_key.sh.j2
        dest: /tmp/import_ipfs_key.sh
        mode: "0700"

    - name: import ipfs key
      ansible.builtin.command:
        cmd: /tmp/import_ipfs_key.sh

    - name: cleanup ipfs key
      ansible.builtin.file:
        path: "/tmp/{{ ipfs_key_name }}.key"
        state: absent

    - name: cleanup ipfs key import script
      ansible.builtin.file:
        path: /tmp/import_ipfs_key.sh
        state: absent

    - name: create bin directory
      ansible.builtin.file:
        path: "/home/{{ ansible_ssh_user }}/bin"
        state: directory

    - name: copy deploy script
      ansible.builtin.template:
        src: publish_totp_ipfs.sh.j2
        dest: "/home/{{ ansible_ssh_user }}/bin/publish_totp_ipfs.sh"
        mode: "0700"

    - name: cronjob to refresh cloudflare gateway
      ansible.builtin.cron:
        name: "totp ipfs refresh cloudflare"
        job: "curl -q https://cloudflare-ipfs.com/ipns/{{ ipfs_key_id }}"
        special_time: "hourly"

    - name: cronjob to refresh ipfs.io gateway
      ansible.builtin.cron:
        name: "totp ipfs refresh ipfs.io"
        job: "curl -q https://gateway.ipfs.io/ipns/{{ ipfs_key_id }}"
        special_time: "hourly"
